/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#43474f",
        "secondary": "#bcc7dd",
        "tertiary-container": "#b7c7e0",
        "on-tertiary-fixed-variant": "#38485d",
        "surface-container-low": "#1b1b1c",
        "primary-container": "#a8c7fa",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-surface-variant": "#c3c6d0",
        "on-surface": "#e5e2e1",
        "secondary-fixed-dim": "#bcc7dd",
        "inverse-on-surface": "#303030",
        "on-tertiary": "#223145",
        "surface-dim": "#131313",
        "tertiary-fixed-dim": "#b8c8e1",
        "on-secondary-fixed": "#111c2c",
        "surface-bright": "#393939",
        "surface-container": "#202020",
        "tertiary": "#d3e3fd",
        "on-primary": "#0a315b",
        "surface-container-highest": "#353535",
        "on-secondary-container": "#aab6cb",
        "on-tertiary-container": "#445368",
        "primary-fixed-dim": "#a9c8fb",
        "outline": "#8d9199",
        "surface-container-high": "#2a2a2a",
        "on-background": "#e5e2e1",
        "on-error": "#690005",
        "primary-fixed": "#d5e3ff",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-fixed": "#001c3b",
        "on-tertiary-fixed": "#0c1c2f",
        "tertiary-fixed": "#d4e4fe",
        "surface": "#131313",
        "on-secondary": "#263142",
        "primary": "#d3e2ff",
        "secondary-fixed": "#d8e3f9",
        "background": "#131313",
        "on-secondary-fixed-variant": "#3c4759",
        "surface-tint": "#a9c8fb",
        "inverse-primary": "#405f8c",
        "on-primary-fixed-variant": "#274773",
        "surface-variant": "#353535",
        "secondary-container": "#3c4759",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e5e2e1",
        "on-primary-container": "#33537f"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "space-sm": "0.5rem",
        "gutter-mobile": "0.25rem",
        "margin": "1.5rem",
        "space-xs": "0.25rem",
        "gutter": "1rem",
        "margin-mobile": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-md": "1rem"
      },
      fontFamily: {
        "title-md": ["Roboto Flex"],
        "display-lg": ["Roboto Flex"],
        "headline-lg-mobile": ["Roboto Flex"],
        "headline-sm": ["Roboto Flex"],
        "title-lg": ["Roboto Flex"],
        "body-sm": ["Roboto Flex"],
        "body-md": ["Roboto Flex"],
        "title-sm": ["Roboto Flex"],
        "label-lg": ["Roboto Flex"],
        "label-sm": ["Roboto Flex"],
        "headline-md": ["Roboto Flex"],
        "label-md": ["Roboto Flex"],
        "body-lg": ["Roboto Flex"],
        "display-md": ["Roboto Flex"],
        "headline-lg": ["Roboto Flex"]
      },
      fontSize: {
        "title-md": ["16px", { lineHeight: "24px", letterSpacing: "0.15px", fontWeight: "500" }],
        "display-lg": ["57px", { lineHeight: "64px", letterSpacing: "-0.25px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "0px", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "32px", letterSpacing: "0px", fontWeight: "400" }],
        "title-lg": ["22px", { lineHeight: "28px", letterSpacing: "0px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.4px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0.25px", fontWeight: "400" }],
        "title-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.1px", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.1px", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.5px", fontWeight: "500" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "0px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.5px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0.5px", fontWeight: "400" }],
        "display-md": ["45px", { lineHeight: "52px", letterSpacing: "0px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "0px", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
};
